### ISSUE TITLE
Server Side Encryption does not work

### ISSUE THREAD

**Issue by toidi** [bradleyg/django-s3direct#101]
`x-amz-server-side​-encryption` fields present in policy object, but not in form fields as required by documentation.

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html#post-object-sse-specific-request-headers

**Comment by elioscordo** [comment]
https://github.com/bradleyg/django-s3direct/pull/118/files

**Comment by bradleyg** [comment]
Think this was fixed in #114 and #118
