### ISSUE TITLE
File names encoding is broken in render()

### ISSUE THREAD

**Issue by macwis** [bradleyg/django-s3direct#112]
Django Version:	1.9.1
Exception Type:	UnicodeEncodeError
Exception Value:	
'ascii' codec can't encode characters in position 138-139: ordinal not in range(128)
Exception Location:	venv/local/lib/python2.7/site-packages/s3direct/widgets.py in render, line 47

Details:

venv/local/lib/python2.7/site-packages/s3direct/widgets.py in render

            name=name) ...
▼ Local vars
Variable	Value
self	
<s3direct.widgets.S3DirectWidget object at 0x7f______>
attrs	
{u'id': u'id_res'}
value	
u'https://s3-eu-west-1.amazonaws.com/mybucket/sthsth\xcc\x81.pdf'
name	
'res'

--
Alphabet signs in the filename which break it are:
 Ì

**Comment by bradleyg** [comment]
This should e fixed in the latest release.
