### ISSUE TITLE
Batch Uploading

### ISSUE THREAD

**Issue by Connotating** [bradleyg/django-s3direct#113]
Hey Django-S3Direct team, I love the work that you all are doing, I've installed this repo through pip and I've been following the updates however I've noticed that there is no way to batch upload files. I've tried to get around this by packing files and images into a single set and loading them through s3direct however it would only take the very first file chosen.

Is there a way to do batch uploading through s3direct? If not is there a way to potential hack together a solution?

**Comment by bradleyg** [comment]
Sorry there isn't at the moment, and the reason is that each file is associated with a single database entry right now. Allowing multiple files would take a lot of reworking, and isn't currently on the roadmap. Sorry!
