### ISSUE TITLE
Permanent redirect bucket url

### ISSUE THREAD

**Issue by Lzok** [bradleyg/django-s3direct#117]
I am using this package in our project and yesterday I saw something that is not documented on the repo. In the core of the package, it searchs for a key in settings called 'S3DIRECT_URL_STRUCTURE' and by default it is `https://{0}/{1}` that results in 'https://s3.amazonaws.com/your-bucket-name'. Using this structure, my bucket throw an error with code `PermanentRedirect` and it give me the new endpoint: `your-bucket-name.s3.amazonaws.com`.
To solve this, I have to set the 'S3DIRECT_URL_STRUCTURE' key in my `settings` as following `https://{1}.{0}` that results in `your-bucket-name.s3.amazonaws.com`.

I hope it helps someone.
Regards.

**Comment by bradleyg** [comment]
Thanks for the report. Which region was your bucket in? I'm trying to reproduce here and can't :(

**Comment by Lzok** [comment]
@bradleyg Your welcome.
The repo is in `us-east-2` US East (Ohio)

**Comment by kltdwrds** [comment]
@bradleyg im having the same issue with `us-east-2`  - switching to us-east-1 works for me.  

get_upload_params view:
```
    bucket = dest.get('bucket') or settings.AWS_STORAGE_BUCKET_NAME
    region = dest.get('region') or getattr(settings, 'S3DIRECT_REGION', None) or 'us-east-1'
    endpoint = 's3.amazonaws.com' if region == 'us-east-1' else ('s3-%s.amazonaws.com' % region)

    # AWS credentials are not required for publicly-writable buckets
    access_key_id = getattr(settings, 'AWS_ACCESS_KEY_ID', None)

    bucket_url = 'https://{0}/{1}'.format(endpoint, bucket)
```

**Comment by bradleyg** [comment]
I think this is fixed, in the latest. I just tried creating a bucket in us-east-2 and seemed to work ok.

The issue with switching to your-bucket-name.s3.amazonaws.com is that if your bucket has a period (.) in it, the SSL wildcard fails.
