### ISSUE TITLE
IAM Role Support has been lost

### ISSUE THREAD

**Issue by tom-dalton-fanduel** [bradleyg/django-s3direct#121]
It looks like [this](https://github.com/bradleyg/django-s3direct/pull/114/files#diff-a29d4fa1e2736f44e8585476c085b19cL64) change in #114 has reverted the support for using the instance's IAM role to provide the credentials rather than the config file. That functionality is pretty important to me, can we get it back?

NB, the above merged PR hasn't yet been released, so the functionality is still present in the latest package (0.4.10), but looks like it is going to be lost in 1.x?

**Comment by bradleyg** [comment]
Ahh, I missed that as I don't use it myself. Please use <1.0 for now, I'll try and get this added to 1.x.

**Comment by tom-dalton-fanduel** [comment]
:heart: thanks!

**Comment by bradleyg** [comment]
Fixed in the latest release thanks to @fmitra
