### ISSUE TITLE
bundled.js missing in project?

### ISSUE THREAD

**Issue by mbrochh** [bradleyg/django-s3direct#122]
It seems like there is only a `scripts.js` file but in `widgets.py` it actually referenced `bundled.js`, which does not exist in this git repo.

Do we need to bundle that manually?

EDIT:

I got it working by going into my venv into the s3direct folder, then running:

```
npm install -g browserify
yarn install
yarn build
```

But surely, that can't be the desired way to use this package?

**Comment by bradleyg** [comment]
If you are installing from PyPI it should be included, if not then you will
need to build the package first using npm build.

**Comment by mbrochh** [comment]
Understood! Thank you!
