### ISSUE TITLE
The CSRF token variable name is "_csrf" instead of "csrftoken" on cookie

### ISSUE THREAD

**Issue by delete** [bradleyg/django-s3direct#123]
Hi.

**Details**:
I'm trying to upload a image from Django admin...

Doing the POST request to *get_upload_params/*, I'm getting 403 because the script tries to get the CSRF token from a **csrftoken** variable that does not exists on my cookie. The variable name is **_csrf**. [This line](https://github.com/bradleyg/django-s3direct/blob/master/s3direct/static/s3direct/js/scripts.js#L174)

Someone else has/had this problem?

Django version: **1.8**

**Comment by delete** [comment]
I did this little fix for me [here](https://github.com/delete/django-s3direct/commit/efbe1426ea559d2d0456331faaab6498002dfa6d), and it's working like a charm:
` headers             = {'X-CSRFToken': Cookies.get('csrftoken') || Cookie.get('_csrf')};`

I would be happy to do a PR, if you want @bradleyg. Let me know. :smile:

**Comment by delete** [comment]
I'm using Askbot and they troll me. 
They rewrote CSRF variable name and I have no ideia why.

I just removed the code from Askbot and everything works. Sorry for the trouble I created.  :disappointed: 

Btw, thanks for the great package!

**Comment by bradleyg** [comment]
Ahh, this raises a great point though! If the user has set the Django [CSRF_COOKIE_NAME](https://docs.djangoproject.com/en/1.11/ref/settings/#csrf-cookie-name) variable then s3direct won't work :) I'll leave this issue open, and I'll see if we can accomodate for that variable in a new release. Thanks for spotting the issue!
