### ISSUE TITLE
No error on file upload fail ?

### ISSUE THREAD

**Issue by Brakkar** [bradleyg/django-s3direct#125]
I tried to set a wrong aws credential to see how it would behave. Uploaded file fails to upload, but there is no error message, nothing. Just black upload bar.
I'm testing on macos + safari.

Is there any callback, signal to intercept when an upload goes wrong ? What is supposed to happen ?

**Comment by ByrdOfAFeather** [comment]
There should be a forbidden error in the Javascript console I believe. I'm not sure how Safari's Inspect element works, but Vivaldi caught the error and displayed it. You could probably handle it in the <script></script> section of an overloaded admin template file.
