### ISSUE TITLE
InvalidPart: one or more of the specified parts could not be found

### ISSUE THREAD

**Issue by ByrdOfAFeather** [bradleyg/django-s3direct#130]
Installed, setup everything through docs, getting this error and the upload bar stuck at the end. Googled around some and not sure if the problem is in my Django config or my AWS config. Any help? 

Edit: Just found out that no error is outputed if I simply upload the file manually (not through the website).

EDIT: JUST FOUND OUT THE HARD WAY: MAKE SURE TO USE THE CORS CONFIG PROVIDED AND NOT ONE FROM ANOTHER TUTORIAL.

**Comment by bradleyg** [comment]
Out of interest, where is the other tutorial?

**Comment by ByrdOfAFeather** [comment]
Heroku docs fir AWS use a different default CORS cofig file. I don't know CORS or XML so I just assumed they did the same thing, they did not.
