### ISSUE TITLE
Credentials & role problems on AWS Lambda with both 0.4.10 and 1.0.3

### ISSUE THREAD

**Issue by Bartvds** [bradleyg/django-s3direct#131]
I'm trying to deploy django-s3direct to a AWS Lambda (with Zappa framework) and I have trouble with the credentials.

I see ticket #121 noting Role support is problematic in 1.0.x so I went with 0.4.10 instead,

It works fine locally with access keys for a user with the required IAM policy for my upload bucket, but as soon as I deploy and use a role (with same policy attached) I get errors from the code here: https://github.com/bradleyg/django-s3direct/blob/208ad2c3a9d6f6ec501fe957db6bdbb007b318fe/s3direct/views.py#L73 (it was difficult finding this code as 0.4.10 is not tagged on Github)

I haven't debugged this yet but I feel this might be related to a difference between EC2 and Lambda?

Anyway, I tried using 1.0.3 (also not tagged), it allows `get_upload_params` but then gives error 500 on `get_aws_v4_signature`,  and when I browse the CloudWatch logs I see "AttributeError: 'Settings' object has no attribute 'AWS_SECRET_ACCESS_KEY'" from "/var/task/s3direct/views.py", line 86, in generate_aws_v4_signature. 

When I check the code in view.py I see no mention at all of roles and it just reads the default `settings.AWS_SECRET_ACCESS_KEY`  which is of course very problematic with a role based system like Lambda/Zappa.

**Comment by Bartvds** [comment]
I looked into some libraries for S3 related stuff I use, like https://github.com/etianen/django-s3-storage and it uses a different approach then the credentials lookup code in 0.4.10: they only set the access/secret keys if specified and else let boto3 (botocore) figure it out (and it deals with Lambda just fine).

**Comment by Bartvds** [comment]
Since we needed dajngo-s3direct in a mild crisis I put some hacks into it for now:

The problem was everything in my app is tied to IAM roles, so I couldn't use the regular AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY settings or all other AWS + Django apps would try to use those instead of the regular role based credentials they get from boto.

So I added alternative credential settings into a fork. If anyone needs this, it looks like this:
https://github.com/bradleyg/django-s3direct/compare/master...sociossports:hotfix-secret-key?expand=1

**Comment by bradleyg** [comment]
Hey, I *think* this is fixed in the latest release... Let me know if not.

Thanks!
