### ISSUE TITLE
Possibility to delete file

### ISSUE THREAD

**Issue by MickaelCruzDB** [bradleyg/django-s3direct#132]
Hi, how is possible to delete the file on s3 at the same time is deleted on django database ??
Thanks!

**Comment by bradleyg** [comment]
Not currently, but would love to see a pull request for it! :)

**Comment by MickaelCruzDB** [comment]
Ok thanks for you quick reply. I really need this feature. Do you know how to do using another django plugin? Thanks again

**Comment by bradleyg** [comment]
Sorry, I don't :( 

Closing out.
