### ISSUE TITLE
Tests won't pass

### ISSUE THREAD

**Issue by SehgalDivij** [bradleyg/django-s3direct#134]
Ran python3 manage.py test and got the following output:

Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...............EF
======================================================================
ERROR: test_urls (s3direct.tests.WidgetTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/divij/django-s3direct/example/s3direct/tests.py", line 65, in test_urls
    resolved_url = resolve('/get_upload_params/')
  File "/home/divij/.local/lib/python3.5/site-packages/django/urls/base.py", line 27, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/divij/.local/lib/python3.5/site-packages/django/urls/resolvers.py", line 392, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 's3direct.urls' from '/home/divij/django-s3direct/example/s3direct/urls.py'> (None:None) ^s3direct/>], [<RegexURLResolver <module 'cat.urls' from '/home/divij/django-s3direct/example/cat/urls.py'> (None:None) ^form/>]], 'path': 'get_upload_params/'}

======================================================================
FAIL: test_widget_html (s3direct.tests.WidgetTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/divij/django-s3direct/example/s3direct/tests.py", line 71, in test_widget_html
    self.assertEqual(widget.render('filename', None), HTML_OUTPUT)
AssertionError: '<div[31 chars]rl="/s3direct/get_upload_params/" data-signing[490 chars]v>\n' != '<div[31 chars]rl="/get_upload_params/" data-signing-url="/ge[472 chars]v>\n'

----------------------------------------------------------------------
Ran 17 tests in 1.064s

FAILED (failures=1, errors=1)
Destroying test database for alias 'default'...

Never run tests before so don't know much about this.

**Comment by bradleyg** [comment]
This should be fixed in the latest release.

Thanks
