### ISSUE TITLE
Modelform field override issue

### ISSUE THREAD

**Issue by ethandrower** [bradleyg/django-s3direct#142]
Hey everyone, I'm having a really tough time getting the s3 uploader widget to work within a modelform.  

With a custom form, the widget is working, so I know my configuration is setup properly. 

Here's the form I'm having trouble with.

    class ManufacturerIntakeFormBase(ModelForm):
        class Meta:
            model = ManufacturerIntake
            fields = '__all__'
            widgets = {
            'technicalSheet': S3DirectWidget(dest='citemed_destination')
             }

    class ManufacturerIntakeForm(ManufacturerIntakeFormBase):

         #techSheet = forms.URLField(widget=S3DirectWidget(dest='cite_destination'), label="Technical Sheet1", required=False)       
           label="Technical Sheet1", required=False) 
                
         class Meta(ManufacturerIntakeFormBase.Meta):

              fields = ManufacturerIntakeFormBase.Meta.fields 
             #fields = ManufacturerIntakeFormBase.Meta.fields + ['techSheet']

I've also tried the config without the widget specification in ManufacturerIntakeFormBase,  and removing the two commented lines.

Any thoughts or input would be greatly appreciated. Thank you!

**Comment by solrates** [comment]
Hi Ethan,

Try defining the destination in the model, then use whatever type of file upload widget you like in the form.

---------------
```
# models.py
# Normal imports
from s3direct.fields import S3DirectField

class ManufacturerIntake(models.Model)
    technicalSheet = S3DirectField(verbose_name="Technical Sheet", dest='citemed_destination') # You may want to change this field name to technical_sheet for Django's naming conventions)

```
---------------
```
# forms.py
from .models import ManufacturerIntake

class ManufacturerIntakeFormBase(ModelForm):
    class Meta:
        model = ManufacturerIntake
        fields = '__all__'
        widgets = {
        'technicalSheet': ClearableFileInput() # or whatever you file upload widget you prefer
         }
```
-------------------

Good luck! 

Cheers,

Dustin

**Comment by Timtech4u** [comment]
Hello, I've the same, upload is successful when using the Django Admin.

But on the form doesn't submit, it just reloads retaining all information but clearing the selected image.

**Comment by bradleyg** [comment]
Hi @Timtech4u, I'm going to close this issue due to inactivity, but please let me know if this is still and issue and I can take a deeper look.
