### ISSUE TITLE
Sorry, could not get upload URL.

### ISSUE THREAD

**Issue by simwes** [bradleyg/django-s3direct#147]
Hello,

I have implemented the settings as in the tutorial but when I try to upload files I get the message: 
Sorry, could not get upload URL.
End from the backend Django gives me this error: 

"POST /s3direct/get_upload_params/ HTTP/1.1" 404 45"POST /s3direct/get_upload_params/ HTTP/1.1" 404 45
In the setting I have specified:

AWS_ACCESS_KEY_ID='…'
AWS_SECRET_ACCESS_KEY='…'
AWS_STORAGE_BUCKET_NAME='…'
S3DIRECT_REGION='…'

Where is do I do wrong ?
Thank you !

**Comment by bradleyg** [comment]
Closing out, please reopen if this is still an issue.
