### ISSUE TITLE
Avoid upload of file with whitespaces

### ISSUE THREAD

**Issue by MickaelCruzDB** [bradleyg/django-s3direct#149]
Hi! 
Thanks for your awesome plugin! Works really well.
I would like to avoid an upload of file containing spaces. 
How can I manage that ?

Thanks!

**Comment by karnatikirankumar** [comment]
Please let me know if you fix that?

**Comment by bradleyg** [comment]
I'm afraid this isn't possible, as S3direct can't actually read the file (it's sent directly to Amazon S3).

**Comment by jaradc** [comment]
I managed this with the following code:

```
const slugify = file => {
	return new File([file], file.name.replace(/\s+/g, '-').toLowerCase(), {type: 'video/mp4'});
};

const checkFileAndInitiateUpload = event => {
	const element = event.target.parentElement;
	const file = slugify(element.querySelector('.file-input').files[0]);
	const dest = element.querySelector('.file-dest').value;
	const destCheckUrl = element.getAttribute('data-policy-url');
	const signerUrl = element.getAttribute('data-signing-url');
	const form = new FormData();
	const headers = { 'X-CSRFToken': getCsrfToken(element) };

	form.append('dest', dest);
	form.append('name', file.name);
        .............
```

slugify creates a new File and replaces the spaces in the name and lowercases it. In my case, I only want to allow 'video/mp4'. This seems to work.
