### ISSUE TITLE
Programming Error can't adapt type 'InMemoryUploadedFile'

### ISSUE THREAD

**Issue by leanludwig** [bradleyg/django-s3direct#151]
Hi Guys,

thanks for this great tool.

I've got an issue regarding compatibility with IPhone's.

Is this bug coming from s3-direct? Google can't find anything regarding this issue.

thanks in advance
Ludwig

![whatsapp image 2018-05-03 at 11 02 26](https://user-images.githubusercontent.com/35435248/39575312-559b7932-4eda-11e8-8236-39ffe14174a9.jpeg)
![whatsapp image 2018-05-03 at 11 02 28 1](https://user-images.githubusercontent.com/35435248/39575319-5a32e796-4eda-11e8-902c-3218d207ec24.jpeg)
![whatsapp image 2018-05-03 at 11 02 28](https://user-images.githubusercontent.com/35435248/39575320-5a4d595a-4eda-11e8-8caf-2112c2196ce9.jpeg)
![whatsapp image 2018-05-03 at 11 02 27 1](https://user-images.githubusercontent.com/35435248/39575321-5a66ea64-4eda-11e8-8ee5-24ca3d6ba720.jpeg)
![whatsapp image 2018-05-03 at 11 02 27](https://user-images.githubusercontent.com/35435248/39575322-5a920ed8-4eda-11e8-9806-72d606d15ccf.jpeg)
![whatsapp image 2018-05-03 at 11 02 26 1](https://user-images.githubusercontent.com/35435248/39575324-5aba452e-4eda-11e8-8613-10a2954cc428.jpeg)

**Comment by bradleyg** [comment]
Closing out, if this is still an issue feel free to reopen.

Thanks
