### ISSUE TITLE
ap-south region urls begin with 's3.'

### ISSUE THREAD

**Issue by vishalpathak24** [bradleyg/django-s3direct#156]
https://github.com/bradleyg/django-s3direct/blob/b0b4ef267fc2d66c939766a5a622a6b889264d70/s3direct/views.py#L56

ap-south region also have urls with 's3.ap-south-1' it will be great if keep these urls consistent

**Comment by bradleyg** [comment]
Think I prefer to keep them consistent, but the other way. So sticking with "s3-".
