### ISSUE TITLE
Using this inside of a larger form

### ISSUE THREAD

**Issue by joshkpeterson** [bradleyg/django-s3direct#158]
It would be really great to have this be a non-form widget that actually uses a separate hidden form on the page or something. I'm trying to use this within an existing form, and I can't, because it's built to be its own form. So in order to use it I'd have to make my existing form a dummy form and populate a hidden form with js.

**Comment by bradleyg** [comment]
You should be able to add this field to your existing Django form. Take a look at the [docs](https://github.com/bradleyg/django-s3direct#formspy). Closing out, please reopen if you still have an issue :)
