### ISSUE TITLE
Incompatible with Django 2.0

### ISSUE THREAD

**Issue by iMerica** [bradleyg/django-s3direct#163]
# Steps to Reproduce
```
from s3direct.fields import S3DirectField
```
# Expected Results
I'm expecting that I can use this Django model field per the documentation.

# Actual Results
```
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```

**Comment by akashp1997** [comment]
I don't think that the plugin is incompatible with Django 2.0 as I have a running version of my project using this plugin to store media files directly to an S3.

**Comment by bradleyg** [comment]
Tested with Django 2 and all seems to be working fine. Closing out, please reopen if you still have this issue.
