### ISSUE TITLE
Access to XMLHttpRequest has been blocked by CORS policy.

### ISSUE THREAD

**Issue by WouterMoedt** [bradleyg/django-s3direct#168]
Hello, I am running into an error when I attempt to upload an image (or any file really) on my admin portal. I cannot upload anything, and when I 'inspect element' I can see the following issue:

![cors](https://user-images.githubusercontent.com/42706462/49884055-97302900-fdf9-11e8-82e5-9ee71c431fea.png)

> Access to XMLHttpRequest has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I do have the CORS settings as defined in the documentation of S3direct. Would anyone know what I could try to do to resolve this?

Thanks!

**Comment by ArsenBespalov** [comment]
CORS setting read this: https://github.com/bradleyg/django-s3direct#s3-cors

**Comment by bradleyg** [comment]
Closing out, if this is still an issue please reopen.

Thanks

**Comment by sskaditya** [comment]
The same issue persists even after we did all of these
S3 cors settings
<CORSConfiguration>
    <CORSRule>
        <AllowedOrigin>http://localhost:8000</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <ExposeHeader>ETag</ExposeHeader>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>

My settings.py 

AWS_ACCESS_KEY_ID = ' '
AWS_SECRET_ACCESS_KEY = ' '
AWS_STORAGE_BUCKET_NAME = 'new'
AWS_S3_REGION_NAME = 'ap-south-1'
AWS_S3_ENDPOINT_URL = 'https://s3.amazonaws.com'
S3DIRECT_REGION = 'ap-south-1'
S3_DIRECT_REGION = 'ap-south-1'
S3DIRECT_DESTINATIONS = {
    'primary_destination': {
        'key': 'uploads/',
        'allowed': ['image/jpg', 'image/jpeg', 'image/png', 'video/mp4'],
    },
    'region': 'ap-south-1'
}

**Comment by srix** [comment]
I am also getting the same error. I noticed that if I change the region to us-east-1 the file upload works, for the same CORS setting. Is ap-south-1 supported?
