### ISSUE TITLE
Allow a way to configure `allowS3ExistenceOptimization`

### ISSUE THREAD

**Issue by batpad** [bradleyg/django-s3direct#175]
Let me start off describing the problem we are facing.

We have two separate models in Django that both have `s3direct` fields, with different destination paths. So, say, model A that saves to `dest/a/` and model B that saves to `dest/b/` - now a user uploads a file `foo.jpg` to model A, and that gets saved at `/dest/a/` - then user goes to model B and happens to upload the same file. I would expect that file to get uploaded to `/dest/b/` but instead, the location of the file in Model B points to the existing file at `/dest/a/`. This was surprising, and in our case, causes undesirable behaviour as we have parts of code that expect uploads from Model A to always be at `/dest/a/` and uploads from Model B to always be at `/dest/b/`

It seems this behaviour comes from options passed to the underlying `Evaporate` library that handles the uploading to s3, specifically this line: https://github.com/bradleyg/django-s3direct/blob/master/src/index.js#L169 . It would be great to be able to pass in configuration from the outside to specify whether or not to enable this behaviour. I can imagine that it is useful in lots of cases, but can also be unwanted in others. If this seems reasonable, am happy to submit a PR.

Thank you for a wonderful library!

**Comment by bradleyg** [comment]
So, I didn't really understand how much of an issue this was until your detailed explanation, so thanks for that. Some body actually created a pull request for this https://github.com/bradleyg/django-s3direct/pull/157, but I wanted to ensure it remained optional. Would love a PR for this!

Thanks

**Comment by bradleyg** [comment]
Guess it should even be disabled by default...

**Comment by bradleyg** [comment]
Fixed in 962a55c3c0d305b19555f6b790b7a7a0e8af1b32, thanks!
