### ISSUE TITLE
django-s3direct styles in index.css are over-writing django admin base.css styles

### ISSUE THREAD

**Issue by calcutec** [bradleyg/django-s3direct#176]
Ran an initial pip install and collectstatic.  Basic html tags styles, <h1>, <h2>, <h3>, etc., from the django admin base.css, are being overwritten by those from the index.css file kept in the django-s3direct dist folder. Please see attached.

Are these supposed to be scoped or name-spaced somehow? I like the changes in the newer version but of course have to keep the rest of the basic admin styling intact

<img width="1265" alt="styles_overwritten" src="https://user-images.githubusercontent.com/2286846/54402933-7c917880-46a4-11e9-8757-8a5480c7e296.png">

**Comment by bradleyg** [comment]
Hmm, this is a problem, can't believe it's never been spotted before..

**Comment by calcutec** [comment]
Yes.  It never happened in versions where css was split between bootstrap-progress.min.css and styles.css. 

The most noticeable problems are coming from the styling for "letter-h four, three, two, etc." tags that are in the bootstrap part of the new dist/index.css file. These aren't in the earlier "bootstrap-progress.min.css" which, as would be expected, is confined to the progress bar classes and some clearfixes. Maybe a broader version of the bootstrap css got in there by mistake?

Reverting for now to the earlier version I had been using.

Thanks for the quick response and work on this great library

**Comment by bradleyg** [comment]
Fixed in 7098cb2cd1c91b17ac1878e8d8e94ecdfbdbb1c5
