### ISSUE TITLE
black progress bar when uploading image

### ISSUE THREAD

**Issue by Iv4nnn** [bradleyg/django-s3direct#180]
When uploading a file there are no errors in browser console and the django server logs look like this
  `HTTP POST /s3direct/get_upload_params/ 200 [0.19, 127.0.0.1:60400]
HTTP POST /s3direct/get_upload_params/ 200 [0.19, 127.0.0.1:60446]
HTTP POST /s3direct/get_aws_v4_signature/ 200 [0.09, 127.0.0.1:60400]
HTTP POST /s3direct/get_aws_v4_signature/ 200 [0.09, 127.0.0.1:60446]
`. 
s3direct keeps returning 200 status logs in the console 

I am using django 2.0.7

**Comment by dsal1951** [comment]
+1

**Comment by bradleyg** [comment]
Hey, thanks for the report. Does the file actually upload?

**Comment by ekwhoa** [comment]
Having the same issue here, with the file not uploading

**Comment by bradleyg** [comment]
Seems like this is related to bucket config.

**Comment by pushpankar** [comment]
I made the bucket public + I added the configs as mentioned in doc. But I am still getting the log.

**Comment by JMIdeaMaker** [comment]
No solutions to this issue in 3 years?
