### ISSUE TITLE
Use of Mutation Events is deprecated. Use MutationObserver instead.

### ISSUE THREAD

**Issue by Schlepptop** [bradleyg/django-s3direct#192]
The title pretty much says it all, Firefox refuses to listen for the [deprecated](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events) mutation events, thus inserting an upload widget dynamically won't work out of the box.

**Comment by sebalatorre** [comment]
I'm having the same issue on google chrome. Will this be merged? It's was submitted two years ago.

**Comment by Schlepptop** [comment]
I closed the above PR in favor of #239, which doesn't have any merge conflicts.
