### ISSUE TITLE
SignatureDoesNotMatch with MinIO

### ISSUE THREAD

**Issue by zikphil** [bradleyg/django-s3direct#194]
Hi,

I am trying to implement this plugin locally using MinIO as a fake-s3 service. Everytime I try to upload a file I keep getting the following error from MinIO: `initiate error: xxxx/applications/1097889.jpg AWS Code: SignatureDoesNotMatch, Message:The request signature we calculated does not match the signature you provided. Check your key and signing method.status:403`

Has anyone been able to successfully make it work before?

**Comment by shacker** [comment]
I'm seeing the same problem talking to Minio, but assumed I had missed a configuration step somewhere. Any suggestions?

**Comment by cwirz** [comment]
@shacker could you figure it out?
