### ISSUE TITLE
Save original file name

### ISSUE THREAD

**Issue by celiao** [bradleyg/django-s3direct#20]
Is it possible to save/extract the original filename when S3DIRECT_UNIQUE_RENAME = True?  I'd like to view the original filename as a readonly field in the Django admin.

**Comment by invalid-access** [comment]
I don't know if this was resolved, but I solved it by storing a json-ized dict in the base TextField. The dict currently contains the destination file URL as before, and also the original filename.
https://github.com/invalid-access/django-s3direct/commit/c6084daa73e5a2b16cf0fa8bb9fa1b0a018b999e

Pl consider merging if this is a good way to accomplish this.
