### ISSUE TITLE
UnicodeDecodeError in setup.py while installing

### ISSUE THREAD

**Issue by frameartist** [bradleyg/django-s3direct#206]
When installing from pip, or cloning from github and using `python setup.py install`, I have the error below:
```
Traceback (most recent call last):
File "setup.py", line 6, in <module>
    readme = f.read()
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 7202: illegal multibyte sequence
```

Seems that it's related to #148 
A temporary solution is to clone the source code manually and comment out these lines in `setup.py`:
```
#f = open(os.path.join(os.path.dirname(__file__), 'README.md'))
#readme = f.read()
#f.close()
```
```
setup(
...
#long_description=readme,
#long_description_content_type='text/markdown'
...
)
```
After that install using `python setup.py install`

**Comment by bradleyg** [comment]
Thanks for the report, should be fixed in 058b484b997158219b9c0eda34ec6ac3d897f563
