### ISSUE TITLE
[Violation] 'DOMNodeInserted' consider using MutationObserver

### ISSUE THREAD

**Issue by sebalatorre** [bradleyg/django-s3direct#225]
index.js:50 [Violation] Added synchronous DOM mutation listener to a 'DOMNodeInserted' event. Consider using MutationObserver to make the page more responsive.

I'm getting this message on Chrome and Safari. Is it a problem on my end? or it's something that should be fixed on this package?

Please help!

**Comment by bradleyg** [comment]
Should be fixed in the latest release.
