### ISSUE TITLE
Cannot get uploads to work under IE11

### ISSUE THREAD

**Issue by margusholland** [bradleyg/django-s3direct#34]
Works fine under Chrome (Mac/Win), FireFox (Mac/Win), Safari (Mac).

In IE I get the following error:

SCRIPT5007: Unable to get property 'error' of undefined or null reference
File: scripts.js, Line: 136, Column: 21

Digging deeper, I found that in IE the POST /s3direct/get_upload_params/ fails CSRF. 

I’m using the field in Django admin.

**Comment by blah73** [comment]
For what it's worth I had a CSRF failure on get_upload_params with the example and found my OS clock settings caused it.  Can you use javascript to print the date/time out of each browser and see if Internet Explorer has a different date/time?

**Comment by bradleyg** [comment]
Closing this out as all seems to work for me. Feel free to reopen if you're still having issues.
