### ISSUE TITLE
Can't get example working

### ISSUE THREAD

**Issue by derek-adair** [bradleyg/django-s3direct#35]
I was getting a 301 (permanently moved) redirect.  Perhaps I just have my bucket configured improperly, but I changed the example form endpoint to be formatted like {{bucket}}.s3.amazonaws.com and it worked like a charm.

**Comment by derek-adair** [comment]
Oh, also the response from amazon is a 301 (permanently moved) redirect.  Which makes me think that its possible the amazon api has changed?

**Comment by rsadwick** [comment]
The example worked out of the box for me.  I had to adjust the order of my settings I was working within a mezzanine-project.  Once I moved the settings down past my installed_apps, everything works great.
