### ISSUE TITLE
Doesn't work inside of a formset

### ISSUE THREAD

**Issue by dwegner79** [bradleyg/django-s3direct#37]
I am trying to use it as part of a formset but it doesn't seem to work. Is there a special way to make it work with formset?

**Comment by bradleyg** [comment]
How is it not working? An error thrown? No progress bar? Alert box?

**Comment by dwegner79** [comment]
there is no error however the widget doesn't work properly, the progress bar (empty) and the remove link both appear before the file is chosen and the upload file action behaves like the django default fileupload field

**Comment by bradleyg** [comment]
Sounds like you are either missing the [URL config](https://github.com/bradleyg/django-s3direct#urlspy) or ```{{ form.media }}``` from your [template](https://github.com/bradleyg/django-s3direct#templatesformhtml).

**Comment by dwegner79** [comment]
no, I have the url config and {{ form.media }} in there. If I do a regular form (no formset) it works properly however as soon as I put it in a formset it breaks

**Comment by bradleyg** [comment]
Can you post your form?
