### ISSUE TITLE
(De)serialize S3DirectFIeld 

### ISSUE THREAD

**Issue by shiranian** [bradleyg/django-s3direct#39]
Does the S3DirectField support deserializing? I am trying to find a way to import images already uploaded and import them into a database. I have used deserialization to include these files with their URLs to S3, but if I want to change the field for the model from URL to S3Direct I need to associate the image urls with the files. Any thoughts? Thanks!

**Comment by bradleyg** [comment]
I think just changing the field would work fine. S3Direct actually stores URLs, not standard Django file objects.

**Comment by shiranian** [comment]
Thanks! It worked!
