### ISSUE TITLE
Change status on File Upload when used as form

### ISSUE THREAD

**Issue by SiddharthMantri** [bradleyg/django-s3direct#40]
Hey Bradley, 

I've implemented the `S3DirectWidget` for a `ModelForm`. I'm struggling with figuring out how to know when the file is uploaded so that I can enable and disable a save button. Is there a specific method in using `s3direct` with a `ModelForm`?

**Comment by bradleyg** [comment]
Hey, in the Django admin tool I do this [here](https://github.com/bradleyg/django-s3direct/blob/master/s3direct/static/s3direct/js/scripts.js#L78), if your save button is of ```type=submit``` you could probably just add the class ```.submit-row``` to your form. 

If not you would have to write your own custom logic in the ```disableSubmit``` function.
