### ISSUE TITLE
how to do file uploads via api

### ISSUE THREAD

**Issue by aTylerRice** [bradleyg/django-s3direct#44]
I need to do file uploads via an api. Is there a way I can just send up the data like png or .mov to an endpoint and then also pass up the time of file (png mov etc). How do I save the data to the model programmatically and not through this magical form?

**Comment by endline** [comment]
+1

**Comment by bradleyg** [comment]
Sure, you can call [```get_upload_params```](https://github.com/bradleyg/django-s3direct/blob/master/s3direct/urls.py#L4) with 3 post params:

```
POST /s3direct/get_upload_params
type=video/quicktime
filename=filename.mov
dest=s3DirectDestinationFromSettings
```

Which returns all of the fields required to post directly to S3:
```json
{  
  "policy":"generated-policy",
  "acl":"public-read",
  "signature":"JeEUf7TNFv5qOk3NmKAZaeIRZbk=",
  "form_action":"https://s3-eu-west-1.amazonaws.com/my-bucket",
  "key":"files/filename.mov",
  "Content-Type":"video/quicktime",
  "AWSAccessKeyId":"my-aws-key",
  "success_action_status":"201"
}
```

You can then post the file directly:
```
POST https://s3-eu-west-1.amazonaws.com/my-bucket
policy=generated-policy
acl=public-read
signature=JeEUf7TNFv5qOk3NmKAZaeIRZbk=
key=files/filename.mov
Content-Type=video/quicktime
AWSAccessKeyId=my-aws-key
success_action_status=201
file=binary
```

**Comment by aTylerRice** [comment]
i have this code right now

    content_type = "image/JPEG"
    key = 'uploads/filename.jpg'
    acl = 'public-read'
    bucket = None
    params_raw = create_upload_data(content_type,key,acl,bucket)

    params = { 'policy': params_raw['policy'],'acl':acl,'signature':params_raw['signature'],'key':params_raw['key'],'Content-Type':params_raw['Content-Type'],'AWSAccessKeyId':params_raw['AWSAccessKeyId'],'success_action_status':params_raw['success_action_status'],'file': binary_data}
    r = requests.post(params_raw['form_action'],data=params,files=dict(foo='bar')) 
    return JsonResponse({'request':str(r.text)},safe=False)

but for some reason I am getting back
    {"request": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidArgument</Code>    <Message>Bucket POST must contain a field named 'key'.  If it is specified, please check the order of the     fields.</Message><ArgumentName>key</ArgumentName><ArgumentValue></ArgumentValue><RequestId>A68024822D18802E</RequestId><HostId>qCwAGDupGKUViTrwXYrKHhDdOWJzq1oWpjz+q/yrWzVPLvrmty3JgZEVdHyrs/8NeagWNZQ409s=</HostId></Error>"}

whats the reason for this? sorry to bug you I know this really isn't in the scope for this. Thanks for the great add on and all the help!

**Comment by aTylerRice** [comment]
Problem was that dictionaries aren't ordered in python you must use an ordered dictionary.

**Comment by amitassaraf** [comment]
> Sure, you can call [`get_upload_params`](https://github.com/bradleyg/django-s3direct/blob/master/s3direct/urls.py#L4) with 3 post params:
> 
> ```
> POST /s3direct/get_upload_params
> type=video/quicktime
> filename=filename.mov
> dest=s3DirectDestinationFromSettings
> ```
> Which returns all of the fields required to post directly to S3:
> 
> ```json
> {  
>   "policy":"generated-policy",
>   "acl":"public-read",
>   "signature":"JeEUf7TNFv5qOk3NmKAZaeIRZbk=",
>   "form_action":"https://s3-eu-west-1.amazonaws.com/my-bucket",
>   "key":"files/filename.mov",
>   "Content-Type":"video/quicktime",
>   "AWSAccessKeyId":"my-aws-key",
>   "success_action_status":"201"
> }
> ```
> 
> You can then post the file directly:
> 
> ```
> POST https://s3-eu-west-1.amazonaws.com/my-bucket
> policy=generated-policy
> acl=public-read
> signature=JeEUf7TNFv5qOk3NmKAZaeIRZbk=
> key=files/filename.mov
> Content-Type=video/quicktime
> AWSAccessKeyId=my-aws-key
> success_action_status=201
> file=binary
> ```

Can you update this to the latest version as it have changed since then? I am trying to use this as an API along with React JS frontend but I am not sure the requests I need to make. If you update it I'll submit a PR to the documentation adding how to use with React / Front end JS lib
