### ISSUE TITLE
Increase a value of policy expiration

### ISSUE THREAD

**Issue by user0007** [bradleyg/django-s3direct#45]
expires_in = datetime.utcnow() + timedelta(seconds=60*5)

Value of "5 minutes" fails when uploading large files.

Maybe it's a good thing to make this value configurable via settings?

**Comment by ciokan** [comment]
I think that's the time you have since making the request to actually start posting not "how much time you have to post"

**Comment by bradleyg** [comment]
Yes, that should be how much time you have to post.
