### ISSUE TITLE
Make destination a dict instead a tuple

### ISSUE THREAD

**Issue by jinpark** [bradleyg/django-s3direct#48]
Since there are  a lot of options now, would it be easier to make it into a dict, instead of a tuple?

**Comment by jinpark** [comment]
I can totally take this btw, just wanted to make sure that you're ok with it :)

**Comment by bradleyg** [comment]
Sounds good, I've been wondering if there is a clean way to do it without breaking API... but I don't think there is.

**Comment by jinpark** [comment]
Probably a good way is to create a new version and notify that it breaks backwards compatibility.

**Comment by bradleyg** [comment]
ok, sounds like a fair compromise.

**Comment by ivanvenosdel** [comment]
Just saw this. Excellent idea. I think a way this can be done in a backwards compatible manner is to do some duck-typing to determine if the old version is in use and then internally convert the current style into the same style of dict as the forward version. Those using the old style will be given a deprecation warning and, after the PyPI release, the docs would be updated to show the new style. Eventually, at some TBD date support for the old version could be dropped.

If someone doesn't beat me to it, I will make a note to see if I can fit this in with #62. I think the feature needed for #62 can require the new version as a way to encourage adoption. The dict I spoke of in that ticket can be an 'extra_options' key in the new style.
