### ISSUE TITLE
Doesn't work with eu-central-1 region. It needs HMAC algorithm

### ISSUE THREAD

**Issue by a-olszewski** [bradleyg/django-s3direct#49]
Error: 
<Code>InvalidRequest</Code>
<Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>

Look at those links:
http://stackoverflow.com/questions/28514981/uploading-a-file-to-s3-frankfurt-gets-an-error-authorization-aws4-hmac-sha256
http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html
http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-authentication-HTTPPOST.html

eu-central-1 works only with AWS Signature Version 4

I've made a quick fix for that:

    now_date = datetime.utcnow().strftime('%Y%m%dT%H%M%S000Z')
    raw_date = datetime.utcnow().strftime('%Y%m%d')

    policy_dict = {
            "expiration": expires,
            "conditions": [
                {"bucket": bucket},
                ["starts-with", "$key", ''],
                {"success_action_status": '201'},
                {"acl": acl},
                {"x-amz-credential": '%s/%s/%s/s3/aws4_request' % (access_key, raw_date, region)},
                {"x-amz-algorithm": "AWS4-HMAC-SHA256"},
                {"x-amz-date": now_date},
                {"content-type": content_type},
            ]
        }

    if cache_control:
        policy_dict['conditions'].append({'Cache-Control': cache_control})

    if content_disposition:
        policy_dict['conditions'].append({'Content-Disposition': content_disposition})

    policy_object = json.dumps(policy_dict)

    policy = b64encode(policy_object.replace('\n', '').replace('\r', '').encode())

    date_key = hmac.new('AWS4' + secret_access_key, msg=raw_date, digestmod=hashlib.sha256).digest()
    date_region_key = hmac.new(date_key, msg=region, digestmod=hashlib.sha256).digest()
    date_region_service_key = hmac.new(date_region_key, msg='s3', digestmod=hashlib.sha256).digest()
    signing_key = hmac.new(date_region_service_key, msg='aws4_request', digestmod=hashlib.sha256).digest()

    signature = hmac.new(signing_key, msg=policy, digestmod=hashlib.sha256).hexdigest()

    structure = getattr(settings, 'S3DIRECT_URL_STRUCTURE', 'https://{1}.{0}')
    bucket_url = structure.format(endpoint, bucket)

    return_dict = {
        "policy": policy,
        "success_action_status": 201,
        "x-amz-credential": "%s/%s/%s/s3/aws4_request" % (access_key, raw_date, region),
        "x-amz-date": now_date,
        "x-amz-signature": signature,
        "x-amz-algorithm": "AWS4-HMAC-SHA256",
        "key": key,
        "form_action": bucket_url,
        "acl": acl,
        "content-type": content_type
    }

Note that every region can use v4 version

**Comment by a-olszewski** [comment]
Could you merge that code?

**Comment by a-olszewski** [comment]
look at diff: http://www.diffnow.com/?report=yguzt

**Comment by bradleyg** [comment]
Thanks, can you create a pull request?

**Comment by bradleyg** [comment]
Fixed in 45585089d88e5172294e81f4607f2a3404681837

Thanks for your help :)
