### ISSUE TITLE
Filenames with spaces create error

### ISSUE THREAD

**Issue by kloddant** [bradleyg/django-s3direct#50]
If you try to upload a file that has a name with a space in it, the space is converted to a "+" sign in the Django admin page, but it is left as a space on S3.  This causes an error when trying to save the admin entry, because the widget attempts to search for the file by its S3 key when saving and cannot find the S3 key.  I've found how to fix this.

In scripts.js, in the update function, replace
`url.value = parseURL(xml)`
with 

```
var parsedXML = parseURL(xml);
var path = parsedXML.substr(0,parsedXML.lastIndexOf('/')+1);
url.value = path+name;
```

and add a parameter called "name" to the update function.  Then at the end of the upload function in the same file, add the variable called "file.name" as a third parameter to the update function call.  Huzzah!

**Comment by bradleyg** [comment]
Thanks, possible to do a pull request?

**Comment by kloddant** [comment]
Okay, just did.  And thank you!  This project has saved a great deal of time for me.

**Comment by ivanvenosdel** [comment]
Kloddant's PR will work fine for the model field but will encounter trouble with the URLField examples. 

So if you are coming here in the latter camp, here is how to fix that case without waiting for library changes. This approach takes the philosophy of sanitizing the file names on the server rather than letting S3 play fast and loose with them.

This would go in your settings.py.
```python
import functools

# Though this function could technically live anywhere. Like somewhere you can unit test it...
def safe_key(prefix, file_name):  
    file_name = file_name.replace(' ', '_')
    # Plus any additional file name customization you want.
    key = '/'.join([prefix, file_name])
    return key

S3DIRECT_DESTINATIONS = {
    'a_destination': [
        functools.partial(safe_key, 'someprefix'),
        lambda u: u.is_authenticated(),
        ['image/jpeg', 'image/png'],
        'public-read',
        'somebucket',
    ],
    'another_destination': [
        functools.partial(safe_key, 'anotherprefix'),
        lambda u: u.is_authenticated(),
        ['image/jpeg', 'image/png'],
        'public-read',
        'somebucket',
    ],
}
```
