### ISSUE TITLE
File Manager

### ISSUE THREAD

**Issue by meetbryce** [bradleyg/django-s3direct#55]
Are there plans in the future for an ability to view files that have already been added using s3direct?

Would be great to be able to re-use files that have been uploaded in different places rather than uploading over the top.

Alternatively, is there another package that works with s3direct and/or s3boto that can be used to achieve this functionality?

Thanks.

**Comment by imoran21** [comment]
+1 for this.  Would be great to be able to have a user delete the entry in the table and cascade to deleting the actual file on S3.

**Comment by bradleyg** [comment]
+1 :)

**Comment by dino-webb** [comment]
+1

**Comment by bradleyg** [comment]
This is out of scope for this project, deleting the file from s3 would be nice, which will most likely happen in #154
