### ISSUE TITLE
Using in place of FileField

### ISSUE THREAD

**Issue by ckcollab** [bradleyg/django-s3direct#61]
Hey there, thanks for making this!

I am a little confused on usage, is there anything special you have to do to use this field as a regular file field? I replaced a FileField with this S3 direct field but it gives a URL back when I do `field.file` and that fails when I try to do normal file type interactions? Do I have to download the file manually to interact with it?

**Comment by bradleyg** [comment]
Hey there, unfortunately s3direct is built around URLField, so yes, for the time being you would need to download the file manually.
