### ISSUE TITLE
Uploading multiple files at a time (solved)..but wanted to find the better way

### ISSUE THREAD

**Issue by acamogh** [bradleyg/django-s3direct#64]
Im trying to upload 2 files at a same time. I changed **getUploadURL**inside scripts.js by adding a for loop 
`for(var i=0; i<=el.querySelector('.file-input').files.length-1; i++){`
     `file_set.push(el.querySelector('.file-input').files[i])}`

and added `form.append('type', file[0].type,file[1].type) ` and `form.append('name', (file[0].name,file[1].name))`

I get **Invalid file type ()** when trying to upload. What else should be changed so that 2 files are upload at the same time

**Comment by acamogh** [comment]
I solved the issue. Im now able to upload multiple files. Please find the screenshot of code, also let me know if there is better way to do it

![screen shot 2016-04-17 at 7 59 47 pm](https://cloud.githubusercontent.com/assets/7515396/14587804/381974f8-04d7-11e6-94cd-cc8cf3e8b567.png)

**Comment by bradleyg** [comment]
Hey there, s3direct is not setup to upload multiple files at the same time, so closing this out.

Thanks
