### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by darkicex3** [bradleyg/django-s3direct#70]
Hi ! 

I got this error -> CSRF verification failed. Request aborted.
On this view -> /s3direct/get_upload_params/

Thanks

**Comment by bradleyg** [comment]
I can't reproduce. Please reopen if you are still having this issue.

**Comment by cordery** [comment]
This will happen if CSRF_COOKIE_HTTPONLY = True.  Set to false or comment out.  Would be preferable if django-s3direct pulled the csrftoken from the hidden csrftoken form field instead of from the cookie so this setting wouldnt have to be disabled.

**Comment by tadeo** [comment]
I was getting the error at production under HTTPS, thanks @cordery for pointing me to the solution!

**Comment by bradleyg** [comment]
Reopening per @cordery's findings (CSRF_COOKIE_HTTPONLY) and @tadeo's [PR](https://github.com/bradleyg/django-s3direct/pull/94).
