### ISSUE TITLE
Sorry, failed to upload file: No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by rileycrane** [bradleyg/django-s3direct#82]
While developing locally, I continue to run into a pop up `Sorry, failed to upload file.`  The console shows the issue is:
```
XMLHttpRequest cannot load https://s3-us-west-2.amazonaws.com/BUCKETNAME. 
Response to preflight request doesn't pass access control check: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:8000' is therefore not allowed access.
```

Any advice on how to proceed?  I've updated the CORS policy in S3 to be 
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

**Comment by rileycrane** [comment]
changing region to `S3DIRECT_REGION = 'us-east-1'` fixed the issue.

**Comment by akalinmehmet** [comment]
To prevent misunderstandings for ones facing with this error, S3DIRECT_REGION must be set to your S3 Bucket's region not staticely 'us-east-1'. 

For example, my S3 Bucket stays on 'US-WEST-2' so this value is, for me,
`S3_DIRECT_REGION = 'us-west-2'`
