### ISSUE TITLE
S3 URL encodes key but s3direct does not return the newly encoded key

### ISSUE THREAD

**Issue by RandomJo** [bradleyg/django-s3direct#84]
I'm running into an issue uploading files with a # sign. The upload to S3 works (and thus doesn't show an error in the CMS); however, the S3 reference that gets saved to my model doesn't work because it saves the unencoded version to the database.

For example, s3direct takes a key like "directory/#35 product" and returns "directory/#35+product", when it should return "directory/%2335+product".

**Comment by JosephDev** [comment]
PR #88 I committed decode path. I think you can decode file name and path before you save it into DB. I did the same way and I have no problem with unicode as well.

**Comment by bradleyg** [comment]
Fixed in https://github.com/bradleyg/django-s3direct/pull/88
