### ISSUE TITLE
Preflight response fails for us-west-1

### ISSUE THREAD

**Issue by nliolios24** [bradleyg/django-s3direct#90]
I'm getting a permanent redirect response from amazon when I upload to a bucket in us-west-1
`<Error>
<Code>PermanentRedirect</Code>
<Message>
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
</Message>
<Bucket>tetra-memories-development</Bucket>
<Endpoint>s3.amazonaws.com</Endpoint>
<RequestId>D4FC960AEE757AF2</RequestId>
<HostId>
+g+KnR0ME3pAcTCYNqeE5nvpAVZwZqItp/BGR9s5RpKhAspm3icawHcU5eKOod2FSzgeSPUBAkE=
</HostId>
</Error>`
I noticed that the utils.py file concatenates the region to the url for every region except `us-east-1`. It looks like Amazon has changed the urls of other regions too. Would anyone be willing to help me troubleshoot this?

**Comment by bradleyg** [comment]
I've just tested with us-west-1 and all seems to work fine. Can you post your settings (obviously with redacted keys)?

**Comment by bradleyg** [comment]
It looks like you bucket is in fact located in us-east-1:
```
curl -I https://s3.amazonaws.com/tetra-memories-development | grep region
x-amz-bucket-region: us-east-1
```

Please reopen if you still have issues.
