### ISSUE TITLE
Read me should include put and get authorization for CORS

### ISSUE THREAD

**Issue by solrates** [bradleyg/django-s3direct#95]
Hi,

Thank you so much for your work on this!  It is a terrific tool for django / heroku deployments.  

Not sure if this is specific for me, but I had to add put and get authorization to the CORS configuration file in order to use "acl": "private"

<CORSConfiguration>
    <CORSRule>
        <AllowedOrigin>http://yourdomain.com:8080</AllowedOrigin>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
    </CORSRule>
</CORSConfiguration>

You might want to update that part of the readme so future users don't bump into the same problem.  If you don't, the download links are denied access.

All the best, 

Dustin

**Comment by bradleyg** [comment]
Thanks
