### ISSUE TITLE
Uploads fail with server side encryption

### ISSUE THREAD

**Issue by solrates** [bradleyg/django-s3direct#96]
My uploads fail when I specify server side encryption:

'server_side_encryption': 'AES256'

When I comment it out, everything works fine.  Is that an issue with the app or with S3?

Thanks!

**Comment by bradleyg** [comment]
Is your bucket set up for encryption?
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

**Comment by bradleyg** [comment]
Please feel free to reopen if this is still an issue.
