### ISSUE TITLE
Compatible with Django 1.5?

### ISSUE THREAD

**Issue by ckcollab** [bradleyg/django-s3direct#98]
Hey there, thanks for releasing this! I've used it a couple times with zero problems, but now I'm wanting to use it on a legacy project. I'm concerned, do you think this will be compatible with Django 1.5?

**Comment by bradleyg** [comment]
Hi there, s3direct should [work fine](https://travis-ci.org/bradleyg/django-s3direct) on 1.5. Let me know if you have any specific issues.

Thanks

**Comment by ckcollab** [comment]
Thanks, appreciate it :1st_place_medal:
